### ISSUE TITLE
Splash screen is still shown for customers with licence on AIR 33.1.1.176

### ISSUE THREAD

**Issue by hardcoremore** [Gamua/Adobe-Runtime-Support#373]
Hi @ajwfrost,

I have copied the license file in both:

C:\Program Files\Adobe\Adobe Flash Builder 4.7 (64 Bit)\eclipse\plugins\com.adobe.flash.compiler_4.7.0.349722\AIRSDK\lib

and 

C:\Program Files\Adobe\Adobe Flash Builder 4.7 (64 Bit)\sdks\Flex 4.6.0 - AIR 33.1.1.176\lib

but when I run application from Flash Builder 4.7 splash screen is shown but not in the ADT Window but in separate window.

**Comment by ajwfrost** [comment]
@hardcoremore  I've just checked this here and am getting the expected behaviour.

Could you run something simple from the command line to test it e.g.
```
"C:\Program Files\Adobe\Adobe Flash Builder 4.7 (64 Bit)\sdks\Flex 4.6.0 - AIR 33.1.1.176\bin\adl.exe" application.xml bin
```

And also:
```
"C:\Program Files\Adobe\Adobe Flash Builder 4.7 (64 Bit)\sdks\Flex 4.6.0 - AIR 33.1.1.176\bin\adt" -license
```

Thanks

**Comment by hardcoremore** [comment]
![image](https://user-images.githubusercontent.com/1597791/86341192-417ad600-bc56-11ea-9748-d58dcd1e64e4.png)

**Comment by ajwfrost** [comment]
Thanks - for the ADL one though, can you actually try that on a basic AIR application with the descriptor XML file and the path to the SWF? to see whether that also results in the splash screen appearing?

I'm wondering where Flash Builder is actually looking for the ADL file, can you start this running up and then look in Task Manager, find the ADL task (adl.exe or "Adobe AIR Debug Launcher") and right-click this, and chose "Open File Location". 

thanks

**Comment by hardcoremore** [comment]
> for the ADL one though, can you actually try that on a basic AIR application with the descriptor XML file and the path to the SWF? to see whether that also results in the splash screen appearing?

How to do this?

This is adl file location that task manager opens:

C:\Program Files\Adobe\Adobe Flash Builder 4.7 (64 Bit)\eclipse\plugins\com.adobe.flash.compiler_4.7.0.349722\AIRSDK\bin

**Comment by hardcoremore** [comment]
Also I have set up this as launcher parameters:

![image](https://user-images.githubusercontent.com/1597791/86347332-73903600-bc5e-11ea-99da-cdbc6b02191c.png)

**Comment by ajwfrost** [comment]
Okay thanks .. can you please try a couple of things from a command line:
1) Using the path you've set in the debuglauncher parameter, put "adt -license" on the end instead of "adl64.exe"
2) Copy that path (to adl64.exe) and then after this put the "launchurl" value (i.e. your descriptor file) and then put the "applicationcontentroot" (path to .swf file).

The first one is just to check that this location has a valid adt.lic as the earlier check was at a different location.
The second one is to see whether the problem is purely within ADL, or whether it's something to do with how Flash Builder is invoking it..

thanks

**Comment by hardcoremore** [comment]
When I run 

Copy that path (to adl64.exe) and then after this put the "launchurl" value (i.e. your descriptor file) and then put the "applicationcontentroot" (path to .swf file).

It says that my license file is present and valid.


>     2\. Copy that path (to adl64.exe) and then after this put the "launchurl" value (i.e. your descriptor file) and then put the "applicationcontentroot" (path to .swf file).

I don't understand what exactly I need to do here, can you give a little more explanation

**Comment by ajwfrost** [comment]
So for this, please try running this from the command line:
```
"C:\Program Files\Adobe\Adobe Flash Builder 4.7 (64 Bit)\eclipse\plugins\com.adobe.flash.compiler_4.7.0.349722\AIRSDK\adl64.exe" C:\Adobe_Flash_Builder_Work_Space\ShapesInMotionAndroid\bin-debug\Main-app.xml C:\Adobe_Flash_Builder_Work_Space\ShapesInMotionAndroid\bin-debug
```

**Comment by hardcoremore** [comment]
When I run this, no splash screen is shown. So it must be how Flash Builder is using it.

![image](https://user-images.githubusercontent.com/1597791/86446045-ac3e1700-bd13-11ea-9901-008c0cf26f46.png)

**Comment by ajwfrost** [comment]
Something odd is happening for sure! We've created a build with some profiling in it which will pop up some message boxes during start-up .. see below
https://transfer.harman.com/message/n07bYCMrBnn9GSLtrh0iny

thanks

**Comment by hardcoremore** [comment]
Well once I runed it with command line now it is working fine when license is in place. I tried deleting sdk and copying it again but it still works normally.

How can I reset this license is there some other file that I can delete so that I can force AIR to check and validate license again?

**Comment by ajwfrost** [comment]
This sounds a little like perhaps Flash Builder is caching a copy of the folder or similar! Bit strange.

The check for the license file happens every time you run the ADL process; if you're using ADT to package something, it also checks each time; license validation (against our servers) only happens every week or two.

So is it working now?

**Comment by denisgl7** [comment]
I got the same problem in Intelij
A splash screen appears after not using an iPhone for two weeks. License purchased in January.

**Comment by ajwfrost** [comment]
@denisgl7 is this on MacOS or Windows? And if you can find the location of the ADT binary that IntelliJ is calling, can you please run 
adt -license
to check the status?
And just to confirm, is this just when you’re running the app on the debug player provided in the AIR SDK, or when you’re running in a simulator on MacOS, or when you’ve installed an IPA onto a phone?

Thanks

**Comment by denisgl7** [comment]
Strange, but the problem itself was solved after a couple of hours of work.
I work on Windows. Maybe I shouldn't have rushed to the message.
 But apparently something is sometimes wrong with a license check.

**Comment by ajwfrost** [comment]
I've just looked at the code that's doing this license check. We used to run "adt -license" and check the result, since this seemed the best way of doing it, but there were issues reported with that so we're now examining the license file directly.

The weird thing would be if you're seeing a splash screen during testing on Windows, but not when you're running it on the device. But if you do find it's appearing (in both situations) then it's likely that the license file is considered to be out of date: it should update itself but maybe there's a permissions problem. Running "adt -license" on the command line should show you both whether it's still valid, and whether there is a permissions problem (and it may well be that running on the command line works - in terms of permissions - but running via IntelliJ doesn't...)

We've got someone who's been looking into the licensing mechanism generally, so we'll see if we can address this and e.g. move the license information to the user's %appdata% folder etc..

**Comment by hardcoremore** [comment]
Hi @ajwfrost, sorry for late reply.

> So is it working now?

It is working now, but only worked after I runed it with command line. It looks like after I runed it with command line somwthing was cached and then it worked with Flash Builder as well. Here are the screenshots of pop ups when I runed it with command line.

https://i.ibb.co/bN6kP43/2020-07-08-25.png

https://i.ibb.co/hLx34zd/2020-07-08-24.png

https://i.ibb.co/5sJttpG/2020-07-08-23.png

https://i.ibb.co/fpWLVry/2020-07-08-22.png

https://i.ibb.co/TKSX4cx/2020-07-08-21.png

https://i.ibb.co/VgVRpWw/2020-07-08-20.png


And here are the screenshots when I runned it with Flash Builder 4.7:

https://i.ibb.co/jrPCYGj/2020-07-08-31.png

https://i.ibb.co/84J1ZLJ/2020-07-08-30.png

https://i.ibb.co/J3Vykf9/2020-07-08-29.png

https://i.ibb.co/5kZkbGP/2020-07-08-28.png

https://i.ibb.co/Ws2ft4g/2020-07-08-27.png

https://i.ibb.co/Bf4tFKR/2020-07-08-26.png

**Comment by hardcoremore** [comment]
Hi @ajwfrost,

This is still an issue for me. Every time I install fresh new AIR SDK there is the license issue.

![image](https://user-images.githubusercontent.com/1597791/87282215-5841e800-c4f4-11ea-9e4f-82ee6bea5b82.png)

Now it wont even start with command line with AIR 33.1.1.190.

**Comment by ajwfrost** [comment]
Hi @hardcoremore 
Sorry, trying to see what's going on there:
1) adl64.exe has an "access is denied" error?
2) adl.exe runs though? (app descriptor not found..)
3) the license file isn't writable: please can you change this file/folder so that it's writable? We're planning to move where the license goes so that it's in a standard per-user folder to avoid these sorts of issues..

We'll look at the ADL64 issue, seems odd..

thanks

**Comment by hardcoremore** [comment]
Now I can not run anything from Flash Builder as you can see from the screenshot above. I will try to reinstall SDK now, I don't know what happen but after I tried to run it from command line it stopped working when trying to run it from Flash  Builder as well.

**Comment by ajwfrost** [comment]
@hardcoremore  okay thanks .. so the weird ADL64 problem may have just been a copy issue, but you're still seeing the splash screen? And what do you get with "adl -license" currently?

**Comment by hardcoremore** [comment]
This is what I get now:

![image](https://user-images.githubusercontent.com/1597791/87291099-25512180-c4ff-11ea-8a97-bf789ef0fab4.png)

**Comment by ajwfrost** [comment]
Okay thanks .. so I think you will need to remove the 'read-only' setting from that folder/file - this is something we'll address in the future.

We'll have to look at this again and try to work out why it's triggering the splash: I think we'll add some further details into a log file so that we can see what's happening. Thanks for your help here..

**Comment by hardcoremore** [comment]
This is still an issue for 33.1.1.217 AIR SDK! I can still see splash screen even if I copy license file.
