### ISSUE TITLE
dx tool failed (com.android.dx.cf.code.SimException) unable to build ane with java8

### ISSUE THREAD

**Issue by Xgamefactory** [Gamua/Adobe-Runtime-Support#48]
we are getting **dx tool failed** error when compiling apk with ane that based on mapbox android sdk with java 1.8 compability.

We are successfully generating ane but unable to build apk.

using jdk 1.8.0_181 64bit(tried other version and jre)
android build tool 28 also min sdk version is 27
adobe air windows sdk 31.0.96 (latest)

also tried replacing old adobe air dx.jar as described in another adobe bugtrack https://tracker.adobe.com/#/view/AIR-4198726 and issue posted here #44 

tried all dx.jars including api28 but result is same.

```
dx tool failed:WARNING in com.mapbox.mapboxsdk.log.LoggerDefinition.log:(ILjava/lang/String;Ljava
/lang/String;)V: defining a static interface method requires --min-sdk-version >= 24 (currently 13) for
interface methods: com.mapbox.mapboxsdk.log.LoggerDefinition.log:(ILjava/lang/String;Ljava
/lang/String;)

Uncaught translation error: com.android.dx.cf.code.SimException: ERROR in
com.mapbox.mapboxsdk.http.NativeHttpRequest.executeLocalRequest:(Ljava/lang/String;)V:
invalid opcode ba - invokedynamic requires --min-sdk-version >= 26 (currently 13)

Uncaught translation error: com.android.dx.cf.code.SimException: ERROR in
com.mapbox.mapboxsdk.log.Logger.log:(ILjava/lang/String;Ljava/lang/String;)V:
invoking a static interface method com.mapbox.mapboxsdk.log.LoggerDefinition.log:(ILjava/lang
/String;Ljava/lang/String;)V strictly requires --min-sdk-version >= 24 (blocked at current API level 13)

Uncaught translation error: com.android.dx.cf.code.SimException: ERROR in
com.mapbox.mapboxsdk.maps.MapView.initialiseDrawingSurface:(Lcom/mapbox/mapboxsdk
/maps/MapboxMapOptions;)V:
invalid opcode ba - invokedynamic requires --min-sdk-version >= 26 (currently 13)
3 errors; aborting
```

We will appreciate if anyone have temporary workaround.

Please vote here: https://tracker.adobe.com/#/view/AIR-4198743

**Comment by Xgamefactory** [comment]
we also tried build with and using java sour and target properties set to 1.8 still getting simexceptions because of java8 features like lambda expressions static method interface.
Does anyone faced this issue and have a workaround ? i see many ane developers here if you got solutions please dont be don't be envious and share :)

**Comment by Xgamefactory** [comment]
we have found solution but cannot rebuild adt.jar inside flex sdk without source codes.

**Comment by laokinsham** [comment]
Problem solved here after an edit of "adt.bat" inside of "bin" directory of sdk.

Simply change "@java" to the jre64 install dir, as showed in the following lines

original
@java -jar "%~dp0\..\lib\adt.jar" %*

changed
C:\DEV\Java\jre8-64\bin\java.exe -jar "%~dp0\..\lib\adt.jar" %*

**Comment by tuarua** [comment]
AIR33 is now built against Java8

**Comment by ajwfrost** [comment]
Issue was caused by how the ADT application was calling Android's AAPT application, fixed in AIR SDK 33.0.0.175 (though the workaround from 27 Feb 2019 above looks useful to anyone on older versions..)

**Comment by itlancer** [comment]
I still get such errors with AIR 33.0.1.220 if I try to use ANE with lambda expressions. ANE compiled with AIR 33.0.1.220, java 1.8 compability.
adt.bat patch doesn't help for me - the same errors.

**Comment by itlancer** [comment]
For me now it works fine with AIR 33.0.2.281 when uses Java 8 features.
