### ISSUE TITLE
AIR 33.1.1.444. android armv8. IOErrorEvent errorID=2032 when request https

### ISSUE THREAD

**Issue by Dima107** [Gamua/Adobe-Runtime-Support#758]
Describe your problem in detail. Include the following information:

AIR 33.1.1.444
Android. armv8

I request data using URLLoader in my project. If I request https:// I've got  [IOErrorEvent type="ioError" bubbles=false cancelable=false eventPhase=2 text="Error #2032: Stream Error. URL: https://adservice.google.com/getconfig/pubvendors" errorID=2032]
For example:

```as3
var req:URLRequest = new URLRequest("https://adservice.google.com/getconfig/pubvendors?publisherIds=<my_id>");
var loader:URLLoader = new URLLoader();
loader.addEventListener(SecurityErrorEvent.SECURITY_ERROR, onEeaError);
loader.addEventListener(IOErrorEvent.IO_ERROR, onEeaError);
loader.addEventListener(Event.COMPLETE, onEeaComplete);
loader.load(req);
```
 AIR 33.1.1.406 works good. AIR 33.1.1.444 android armv7 works good too.
 I have problems with armv8 only.
 
 Have someone same issue?

**Comment by mrfrasier** [comment]
I am experiencing the same issue. An app that works fine on iOS can't seem to make any connections to my server on Android.

My avatar fails to load:
`== AVY Error: [IOErrorEvent type="ioError" bubbles=false cancelable=false eventPhase=2 text="Error #2035: URL Not Found. URL: https://keyavy.pokellector.com/1/AnUnown.1612281707.png" errorID=2035]`

Calls to my backend fail as well:
```
 ------------- NetStatusEvent -------------
target: [object NetConnection]
currentTarget: [object NetConnection]
error code: NetConnection.Call.Failed
onAMFError  Error connecting to host
```

I was indeed on an armv8 64 bit build, so thanks to this thread, I tried again with armv7 and things all work fine. So it def seems related to armv8 (I'm using release 444)

I've also been having users in the wild report intermittent connection issues. I will have to check if they are on 64bit builds as well (though I only installed 444 this morning, so it would be an earlier SDK)

**Comment by urthling** [comment]
Seeing same issue on Android armv8 making connections with release .444

**Comment by speego76** [comment]
Seeing same issue on Android armv8

**Comment by abhisheksb164** [comment]
Facing the same issue with armv8 build armv7 working fine.

**Comment by xangel82** [comment]
I have the some Issue on Android with armv8

**Comment by edicsa** [comment]
I have the same Issue on Android with armv8 too

**Comment by balaedit** [comment]
Same issue on both the platform.
Using the below path : 
[Path of Adobe Air SDK of ver 33.1.1.444]\frameworks\libs\air\aircore.swc is getting the issue.

If I use the below SDK :
[Path of Adobe Air SDK of ver 33.1.1.406]\frameworks\libs\air\aircore.swc is working fine.

**Comment by ajwfrost** [comment]
@balaedit can I check, do you mean that if you copy that `aircore.swc` file across from the older SDK to the new one, then it starts working? We're currently looking into the ssl implementation as the expected area causing this problem so I would be surprised if a change to that swc file impacts it..?!

thanks

**Comment by edicsa** [comment]
It stopped working with the latest version of the SDK. Works fine with the previous version.

**Comment by yrozijn** [comment]
Same here.
For investigation purpose, I also listen to HTTP_STATUS and HTTP_RESPONSE_STATUS.
Packaged for armv8 with AIR 3.1.1.444 I get:
```
[HTTPStatusEvent type="httpStatus" bubbles=false cancelable=false eventPhase=2 status=0 redirected=false responseURL=null]
[IOErrorEvent type="ioError" bubbles=false cancelable=false eventPhase=2 text="Error #2032: Stream Error. URL: https://mysite.com/backend.php" errorID=2032]
```

Packaged for armv7, it works fine:
```
[HTTPStatusEvent type="httpResponseStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL="https://mysite.com/backend.php"]
[HTTPStatusEvent type="httpStatus" bubbles=false cancelable=false eventPhase=2 status=200 redirected=false responseURL=null]
```

I can confirm that reverting back to AIR 33.1.1.345 solves the problem.

**Comment by stoff99** [comment]
Yes, same issue here. Its working with ARMV7 but not with ARMV8.
Somebody has the link to the previous AIR SDK please?

**Comment by edicsa** [comment]
https://airsdk.harman.com/release_notes

**Comment by stoff99** [comment]
Thx @edicsa,
didn't realize that Harman implemented an archiv already!

**Comment by ajwfrost** [comment]
Thanks for the input and information here - we've found a difference in configuration in the armv8 (and x86_64) builds of AIR which we believe to be the culprit. Testing should be completed shortly to confirm if this is the case.. if this doesn't fix it, we'll revert the related changes back so that it's working the same as previously in the .406 release, so that we can get some updated/working version out to you asap..

thanks

**Comment by ajwfrost** [comment]
.. and I've just heard, initial test was successful so we'll get this fix properly integrated and kick off a new release ...
thanks

**Comment by muxame** [comment]
Hello Everyone,

Is there any update for this bug? I lost my mind for the past 4 days trying to find a solution and when I reverted the SDK form 33.1.1.4444 to 33.1.1.406 it just worked!  then I came to this forum knowing that you guys facing the same issue. God Help us all.

air is a nice cross-platform development solution but no hot reload and such bugs slowing us down , and remove coding enjoyments 

Thanks

**Comment by urthling** [comment]
Perhaps a notification would suffice?  An escalated issue could trigger one, or something of that nature.  Anyone making use of http on Android armv8 should know not to use this build.

I think you @ajwfrost and your team have been doing a fantastic job, so I'm reluctant to say anything negative -- it would be good to know if something like this happens again, we could get a heads up.  Nothing elaborate necessary I'd say.

**Comment by Gokulv617** [comment]
**I use AIR SDK - 33.1.1.345
Adobe Animate**

I'm also facing the same error in some scenario. Some of my users are saying the level is loaded 100% but does not open. I tested in various scenario but could not find it, loads correctly to me. So I added a text field to trace the error in IOERROR event and published my apk. Now one of the user has sent me the below screenshot and mentioned the same issue. 

### ERROR CODE 2036
```
	loader.load(new URLRequest(strUrl));
	loader.contentLoaderInfo.addEventListener(Event.UNLOAD, unLoadHandler)
	loader.contentLoaderInfo.addEventListener(ProgressEvent.PROGRESS,jusDisplayprogress);
	loader.contentLoaderInfo.addEventListener(IOErrorEvent.IO_ERROR,jusDisplayError);
	loader.contentLoaderInfo.addEventListener(Event.COMPLETE, jusDisplayloadComple);
```

```
function jusDisplayError(event: IOErrorEvent): void {
	trace("ioErrorHandler: " + event);
	trace("ioErrorHandler: " + event.errorID);
	if (monitor.available) {          //internet is available
		error_txt.text = "err-loading-" + event.errorID;
	} else {
		error_txt.text = "err-internet-" + event.errorID;
	}
}
```

![img_20210423](https://user-images.githubusercontent.com/43432782/115818234-f961b580-a419-11eb-9978-03193892ff13.png)

**Comment by ajwfrost** [comment]
@Gokulv617 if you're using .345 of the SDK, and are seeing error 2036, then this implies it's a different problem! There are a few places where error 2036 is thrown but all of them require the connection to have been opened first (which means it's not the same issue as we're seeing with https via 444). Particularly if the process indicator has hit 100%, this seems to suggest that the data has loaded and then there's a failure in parsing this, or similar..

**Comment by Gokulv617** [comment]
> @Gokulv617 if you're using .345 of the SDK, and are seeing error 2036, then this implies it's a different problem! There are a few places where error 2036 is thrown but all of them require the connection to have been opened first (which means it's not the same issue as we're seeing with https via 444). Particularly if the process indicator has hit 100%, this seems to suggest that the data has loaded and then there's a failure in parsing this, or similar..

I have not changed any coding in loading swf's. I use google cloud storage for providing online data to my players. This game is in playstore for more than 3 years. Recently in several of my games, players say this issue. I have checked many times, but still I'm unable to replicate this issue. This has also happened in 64 bit apk particularly. Any suggestions to fix this ?

**Comment by muxame** [comment]
Check your SSL certificate for the URL you are calling by the URLLOADER

AT :- https://www.digicert.com/help/

If all okay and http(s) is working fine .

Make  test apk ,,( test project) with button and URLloder function to test
at Android cell phone ( as the issue only happening at Android cell phones )

Then try to switch between air SDK in my case I downgraded the SDK to
33.1.1.406 an and all is fine so far .

GL

**Comment by Dima107** [comment]
fixed in 33.1.1.476

**Comment by ventr1x** [comment]
This is as always incredible.
No mention, no testing involved. Just pushing out a new live SDK version that literally breaks any kind of remote connection.
We just experienced this, only on uploaded binaries. It's fun to try and debug this issue, losing multiple hours, and more hours from testers that had to cancel everything.
The tech debt with AIR and every single version being massively error riddled is unbearable!

**Comment by marchbold** [comment]
@ventr1x Are you still experiencing this issue?

**Comment by balaedit** [comment]
Dear Sir,
I am still facing this issue in my new release.

I am using Animate CC 2021 and Adobe Air SDK **33.1.1.476**

**While publishing my app using ARMv7 (32 bit), it's working fine in debugging (testing) and release version.**

![WhatsApp Image 2021-05-31 at 12 39 47 AM](https://user-images.githubusercontent.com/37571867/120117489-115fee00-c1ab-11eb-8165-c019da265182.jpeg)

**But when publishing my app using ARMv8 (64 bit), it's working fine in debugging (testing) but getting 2032 error in release version.**

![WhatsApp Image 2021-05-31 at 12 40 31 AM](https://user-images.githubusercontent.com/37571867/120117567-600d8800-c1ab-11eb-94cb-7cb0e45de15c.jpeg)

**Since, playstore didn't publish app without 64bit. Reason :  This release is not compliant with the Google Play 64-bit requirement.**

**I am stuck**. Should I use the older version i.e. AIR SDK 33.1.1.345 which was working fine in all release.
